apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delete-task
  template:
    metadata:
      labels:
        app: delete-task
    spec:
      containers:
      - name: delete-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sqlserverone.database.windows.net,1433;Database=adminDB;Uid=sqluser;Pwd=Hello@123456;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: registryk8ss.azurecr.io/deletetask
        ports:
        - containerPort: 8000
