apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-task-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: / 
spec:
  rules:
  - host: deletetask.xrocketx.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: delete-task
            port: 
              number: 80
