apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-task-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - host: addtask.xrocketx.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: add-task
            port: 
              number: 80
