apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-101
  # namespace: mynamespace
  # labels:
  #   app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-101
  template:
    metadata:
      labels:
        app: myapp-101
    spec:
      containers:
        - name: container-101
          image: vimaleshm/todo-ui:101   # your docker image
          ports:
            - containerPort: 80          # your app port
          # env:
          #   - name: ENVIRONMENT
          #     value: "production"
          #   - name: DB_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-secret
          #         key: DB_URL


