apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      containers:
      - name: get-tasks
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sqlserverone.database.windows.net,1433;Database=adminDB;Uid=sqluser;Pwd=Hello@123456;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          
        image: registryk8ss.azurecr.io/gettasks:latest
        ports:
        - containerPort: 8000
