apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-tasks-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gettask.xrocketx.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: get-tasks
            port: 
              number: 80
